services:
  # Python ML API Service
  - type: web
    name: rhythmiq-ml-api
    runtime: python
    buildCommand: pip install -r requirements-api.txt
    startCommand: python 11_python_api/rhythmiq_api.py
    
  # Java Spring Boot Webapp
  - type: web
    name: rhythmiq-webapp
    runtime: docker
    dockerfilePath: ./07_java_webapp/Dockerfile
    dockerContext: ./07_java_webapp
