services:
  - type: web
    name: rhythmiq-webapp
    env: java
    plan: free
    buildCommand: cd java-webapp && chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: cd java-webapp && java -Dserver.port=$PORT -jar target/rhythmiq-webapp-1.0.0.jar
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m -XX:MaxMetaspaceSize=128m"
      - key: SPRING_PROFILES_ACTIVE
        value: "production"