services:
  - type: web
    name: rhythmiq-webapp
    env: docker
    plan: free
    dockerfilePath: ./java-webapp/Dockerfile
    dockerContext: ./java-webapp
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m -XX:MaxMetaspaceSize=128m"
      - key: SPRING_PROFILES_ACTIVE
        value: "production"