services:
  # Python ML API Service
  - type: web
    name: rhythmiq-python-api
    runtime: python
    buildCommand: pip install -r 09_python_api/requirements.txt
    startCommand: python 09_python_api/rhythmiq_api.py
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false

  # Java Web Application Service
  - type: web
    name: rhythmiq-java-webapp
    runtime: docker
    dockerfilePath: ./06_java_webapp/Dockerfile
    dockerContext: ./06_java_webapp
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PYTHON_API_URL
        value: https://rhythmiq-python-api.onrender.com
